[project]
name = "agent"
version = "0.1.0"
description = "智能体主框架"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp==3.13.2",
    "aiomysql==0.3.2",
    "fastapi==0.127.0",
    "httpx==0.28.1",
    "langchain==1.2.0",
    "langchain-openai==1.1.6",
    "langchain-deepseek==1.0.1",
    "markitdown[docx]==0.1.2",
    "mcp[cli]>=1.25.0",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "tabulate>=0.9.0",
    "langfuse==3.11.0",
    "langfuse-sdk==1.0.0",
    "tiktoken==0.12.0",
    "sqlalchemy==2.0.41",
    "streamlit==1.52.2",
    "streamlit-echarts==0.4.0",
    "pydantic-yaml==1.6.0",
]

[tool.uv.workspace]
members = [
    "agent",
]

