[project]
name = "mcp-server"
version = "0.2.0"
description = "智能体调用工具（逻辑）服务"
requires-python = ">=3.12"
readme = "README.md"
dependencies = [
    "aiohttp==3.13.2",
    "aiomysql==0.3.2",
    "cachetools==6.2.1",
    "fastapi==0.127.0",
    "httpx==0.28.1",
    "langchain==1.2.0",
    "langchain-openai==1.1.6",
    "langchain-deepseek==1.0.1",
    "markitdown[docx]==0.1.2",
    "mcp[cli]==1.25.0",
    "minio==7.2.19",
    "openpyxl==3.1.5",
    "opik==1.9.31",
    "pandas>=2.3.1",
    "pillow==11.3.0",
    "psycopg[binary,pool]==3.2.13",
    "schedule==1.2.2",
    "scipy==1.14.0",
    "tabulate==0.9.0",
    "cvxpy==1.6.7",
    "matplotlib==3.10.7",
    "seaborn==0.13.2",
    "sqlalchemy==2.0.41",
    "langfuse==3.11.0",
    "langfuse-sdk==1.0.0",
    "gmssl==3.2.1",
    "ortools==9.14.6206",
    "pulp==3.3.0",
    "pydantic-yaml==1.6.0",
]

[tool.uv.workspace]
members = [
    "forecast",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

